### PR TITLE
[ADF-PeopleCloudComponent] Fixed failing unit tests

### PR DESCRIPTION
**Pull request by sivakumar414ram**
**Please check if the PR fulfills these requirements**

> - [ ] The commit message follows our [guidelines](https://github.com/Alfresco/alfresco-ng2-components/wiki/Commit-format)
> - [ ] Tests for the changes have been added (for bug fixes / features)
> - [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x")

> - [ ] Bugfix
> - [ ] Feature
> - [ ] Code style update (formatting, local variables)
> - [ ] Refactoring (no functional changes, no api changes)
> - [ ] Build related changes
> - [ ] Documentation
> - [ ] Other... Please describe:

**What is the current behaviour?** (You can also link to an open issue here)

* Fixed failing unit tests

**What is the new behaviour?**

**Does this PR introduce a breaking change?** (check one with "x")

> - [ ] Yes
> - [ ] No

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

**Other information**:

### CODE REVIEW

**Comment by eromano** [comment]
still one test failing   TaskHeaderCloudComponent
    ✖ should display due date
      Chromium 62.0.3202 (Ubuntu 0.0.0)
    Expected '18-12-2018' to be 'Dec 18 2018'.
        at src/lib/task/task-header/components/task-header-cloud.component.spec.ts:98:60
        at ZoneDelegate.push.../../node_modules/zone.js/dist/zone.js.ZoneDelegate.invoke (home/travis/build/Alfresco/[secure]-ng2-components/node_modules/zone.js/dist/zone.js:391:1)
        at AsyncTestZoneSpec.push.../../node_modules/zone.js/dist/zone-testing.js.AsyncTestZoneSpec.onInvoke (home/travis/build/Alfresco/[secure]-ng2-components/node_modules/zone.js/dist/zone-testing.js:714:1)

**Comment by sivakumar414ram** [comment]
> still one test failing TaskHeaderCloudComponent
> ✖ should display due date
> Chromium 62.0.3202 (Ubuntu 0.0.0)
> Expected '18-12-2018' to be 'Dec 18 2018'.
> at src/lib/task/task-header/components/task-header-cloud.component.spec.ts:98:60
> at ZoneDelegate.push.../../node_modules/zone.js/dist/zone.js.ZoneDelegate.invoke (home/travis/build/Alfresco/[secure]-ng2-components/node_modules/zone.js/dist/zone.js:391:1)
> at AsyncTestZoneSpec.push.../../node_modules/zone.js/dist/zone-testing.js.AsyncTestZoneSpec.onInvoke (home/travis/build/Alfresco/[secure]-ng2-components/node_modules/zone.js/dist/zone-testing.js:714:1)

I see these changes recently https://github.com/Alfresco/alfresco-ng2-components/commit/c9dbcdfc8c887df06d144534ebc95ad8b472ff85#diff-dc7c734f2a158b34f3f85efaa40a4811, due to this change the unit test is failing. Is a valid date format? because we have a different date format in both TaskHeaderComponent ('Dec 18 2018')  and TaskHeaderCloudComponent ('18-12-2018'). Which one is a valid date format?

**Comment by eromano** [comment]
@monsterflaw I think your is a really good question. My proposal is.
For now, let's fix the test to reflect that changed that you pointed.
Next step I am going to create an issue where I will ask to make the date format a central configuration that we can get and set from the app.config.json.
What do you think?

**Comment by sivakumar414ram** [comment]
> @monsterflaw I think your is a really good question. My proposal is.
> For now, let's fix the test to reflect that changed that you pointed.
> Next step I am going to create an issue where I will ask to make the date format a central configuration that we can get and set from the app.config.json.
> 
> https://issues.alfresco.com/jira/browse/ADF-4342
> 
> What do you think?

Agree, Fixed the failing unit test

**Pull request merged**
