### PR TITLE
[ACA-3506] - Filter are kept when reloaded

### PR DESCRIPTION
**Pull request by VitoAlbano**
**Please check if the PR fulfills these requirements**

> - [ ] The commit message follows our [guidelines](https://github.com/Alfresco/alfresco-ng2-components/wiki/Commit-format)
> - [ ] Tests for the changes have been added (for bug fixes / features)
> - [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x")

> - [ ] Bugfix
> - [X] Feature
> - [ ] Code style update (formatting, local variables)
> - [ ] Refactoring (no functional changes, no api changes)
> - [ ] Build related changes
> - [ ] Documentation
> - [ ] Other... Please describe:

**What is the current behaviour?** (You can also link to an open issue here)
When refreshing filters selection are lost

**What is the new behaviour?**
When selecting/reloading the page filters are saving their values

**Does this PR introduce a breaking change?** (check one with "x")

> - [ ] Yes
> - [ ] No

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

**Other information**:
https://issues.alfresco.com/jira/browse/ACA-3506

### CODE REVIEW

**Review by eromano — CHANGES_REQUESTED** [review]
Despite the fact is green no e2e has been performed..can you check why?

**Review by DenysVuika — APPROVED** [review]

**Comment by eromano** [comment]
I am going to merge it the test failures are because another problem under investigation

**Review by eromano — CHANGES_REQUESTED** [review]
allowUpdateOnChange I don't see documentation on it

**Pull request merged**
