### PR TITLE
[ADF-3771] use native moment import

### PR DESCRIPTION
**Pull request by DenysVuika**
**Please check if the PR fulfills these requirements**

> - [x] The commit message follows our [guidelines](https://github.com/Alfresco/alfresco-ng2-components/wiki/Commit-format)
> - [ ] Tests for the changes have been added (for bug fixes / features)
> - [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x")

> - [ ] Bugfix
> - [ ] Feature
> - [ ] Code style update (formatting, local variables)
> - [x] Refactoring (no functional changes, no api changes)
> - [ ] Build related changes
> - [ ] Documentation
> - [ ] Other... Please describe:

**What is the current behaviour?** (You can also link to an open issue here)

**What is the new behaviour?**

- use native import for momentjs
- deprecate the use of 3rd party library moment-es6

**Does this PR introduce a breaking change?** (check one with "x")

> - [ ] Yes
> - [x] No

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

**Other information**:
https://issues.alfresco.com/jira/browse/ADF-3771

### CODE REVIEW

**Comment by eromano** [comment]
@DenysVuika should we try the same workaround?

https://github.com/jvandemo/generator-angular2-library/issues/221#issuecomment-355945207

**Comment by DenysVuika** [comment]
@eromano This is how Angular Materials are using it, something undocumented I guess: https://github.com/angular/material2/blob/master/src/material-moment-adapter/adapter/moment-date-adapter.ts#L16

**Comment by eromano** [comment]
maybe we can do the same of : https://github.com/Agamnentzar/moment-es6/blob/master/index.js

**Comment by DenysVuika** [comment]
Closing for now as we need to wait until 'moment' guys provide some proper fix.

**Pull request closed without merging**
