### PR TITLE
[AAE-12065] Add isDefault flag to dropdown

### PR DESCRIPTION
**Pull request by DiogoABastos**
**Please check if the PR fulfills these requirements**

> - [x] The commit message follows our [guidelines](https://github.com/Alfresco/alfresco-ng2-components/wiki/Commit-format)
> - [x] Tests for the changes have been added (for bug fixes / features)
> - [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x")

> - [ ] Bugfix
> - [x] Feature
> - [ ] Code style update (formatting, local variables)
> - [ ] Refactoring (no functional changes, no api changes)
> - [ ] Build related changes
> - [ ] Documentation
> - [ ] Other... Please describe:

**What is the current behaviour?** (You can also link to an open issue here)
If dropdown field had the same id as the `DEFAULT_OPTION.id`, it would be taken as the default option

https://alfresco.atlassian.net/browse/AAE-12065
https://github.com/Alfresco/alfresco-apps/pull/5894

**What is the new behaviour?**
Add `isDefault` flag to allow users to use the `DEFAULT_OPTION.id` as an id, without making such an option the default option
Is compatible with JSON forms previously created

**Does this PR introduce a breaking change?** (check one with "x")

> - [ ] Yes
> - [x] No

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

**Other information**:

### CODE REVIEW

**Review by eromano — CHANGES_REQUESTED** [review]
what happens if isDefault is not present in the JSON because is a form previously created?

**Comment by DiogoABastos** [comment]
> what happens if isDefault is not present in the JSON because is a form previously created?

`isDefault` flag is defaulted to false. The problem is that when the dropdown has the default option enabled, it will be regarded as a normal option because of the `isDefault`'s default value. I'll make some changes to account for that

**Review by eromano — CHANGES_REQUESTED** [review]
can we add a unit that cover this scenario?

**Comment by DiogoABastos** [comment]
No need for this changes anymore. https://alfresco.atlassian.net/browse/AAE-12065?focusedCommentId=1192290

**Pull request closed without merging**
