### PR TITLE
Added new process and forms to simpleapp

### PR DESCRIPTION
**Pull request by cristinaj**
**Please check if the PR fulfills these requirements**

> - [ ] The commit message follows our [guidelines](https://github.com/Alfresco/alfresco-ng2-components/wiki/Commit-format)
> - [ ] Tests for the changes have been added (for bug fixes / features)
> - [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x")

> - [ ] Bugfix
> - [ ] Feature
> - [ ] Code style update (formatting, local variables)
> - [ ] Refactoring (no functional changes, no api changes)
> - [ ] Build related changes
> - [ ] Documentation
> - [ ] Other... Please describe:

**What is the current behaviour?** (You can also link to an open issue here)

**What is the new behaviour?**

**Does this PR introduce a breaking change?** (check one with "x")

> - [ ] Yes
> - [ ] No

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

**Other information**:

### CODE REVIEW

**Comment by cristinaj** [comment]
> if you add it in the app probably you need them also in the resources file?

Yes, but that is part of another PR. Is it necessary to add that stuff in this PR?

**Comment by eromano** [comment]
If you don't need it now can we add it in just that PR?

**Comment by cristinaj** [comment]
> If you don't need it now can we add it in just that PR?

The idea was to have it merged first, because there are many persons that want to modify the simpleapp app. If i don't merge this new app first, they will use the current one so my updates will be lost.

**Comment by eromano** [comment]
not sure is a good practice because if your PR will not be merged in the end we will have this modify inside forever

**Pull request closed without merging**
