### PR TITLE
[ACS-3731] move/copy dialog and content overlaps other than 320px issue fixed

### PR DESCRIPTION
**Pull request by jatin2008**
**Please check if the PR fulfills these requirements**

> - [ x] The commit message follows our [guidelines](https://github.com/Alfresco/alfresco-ng2-components/wiki/Commit-format)
> - [ ] Tests for the changes have been added (for bug fixes / features)
> - [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x")

> - [ x] Bugfix
> - [ ] Feature
> - [ ] Code style update (formatting, local variables)
> - [ ] Refactoring (no functional changes, no api changes)
> - [ ] Build related changes
> - [ ] Documentation
> - [ ] Other... Please describe:

**What is the current behaviour?** (You can also link to an open issue here)
Content is lost, clipped, or obscured when the page is zoomed to 200%, Content overlaps other content at 320px width equivalent

**What is the new behaviour?**
move/copy dialog and content overlaps other than 320px issue fixed

**Does this PR introduce a breaking change?** (check one with "x")

> - [ ] Yes
> - [x ] No

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

**Other information**:

### CODE REVIEW

**Comment by jatin2008** [comment]
before- https://axeauditor.dequecloud.com/api/v1/file/878bf462-efda-11ec-abf3-8f591bbca706

after-
Screenshot from 2022-11-16 16-39-04
Screenshot from 2022-11-16 16-41-17

**Comment by jatin2008** [comment]
after
Screenshot from 2022-11-16 16-51-10
Screenshot from 2022-11-16 16-51-33
Screenshot from 2022-11-16 16-51-39

**Review by MichalKinas — APPROVED** [review]

**Comment by MichalKinas** [comment]
@jatin2008 check out Travis -> linter is failing

**Comment by jatin2008** [comment]
> @jatin2008 check out Travis -> linter is failing

yeah sure, checking

**Pull request merged**
