### PR TITLE
[ADF-4373] Automation test for accurate error messages

### PR DESCRIPTION
**Pull request by marouanbentaleb**
**Please check if the PR fulfills these requirements**

> - [ ] The commit message follows our [guidelines](https://github.com/Alfresco/alfresco-ng2-components/wiki/Commit-format)
> - [ ] Tests for the changes have been added (for bug fixes / features)
> - [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x")

> - [ ] Bugfix
> - [ ] Feature
> - [ ] Code style update (formatting, local variables)
> - [ ] Refactoring (no functional changes, no api changes)
> - [ ] Build related changes
> - [ ] Documentation
> - [x] Other... Please describe:
Automation tests to check that when an error is thrown, accurate message is displayed.

**What is the current behaviour?** (You can also link to an open issue here)

**What is the new behaviour?**

**Does this PR introduce a breaking change?** (check one with "x")

> - [ ] Yes
> - [ ] No

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

**Other information**:
https://issues.alfresco.com/jira/browse/ADF-4250

### CODE REVIEW

**Comment by gmandakini** [comment]
do we want to test for 'back to home' button as well? as I see that has been added as part of this feature.

**Comment by marouanbentaleb** [comment]
I'm not sure it's needed, since the ticket is about the messages.

**Comment by gmandakini** [comment]
will be good to add a case, where we hit the 'back to home' button and home page is loaded fine. only in 1 place should be enough.

**Comment by marouanbentaleb** [comment]
@gmandakini we already test this in C280563

**Comment by eromano** [comment]
can we remove all those new tests and just test the unknown error functionality?

**Pull request merged**
