### PR TITLE
[ACS-7555] column filters

### PR DESCRIPTION
**Pull request by AleksanderSklorz**
**Please check if the PR fulfills these requirements**

> - [x] The commit message follows our [guidelines](https://github.com/Alfresco/alfresco-ng2-components/wiki/Commit-format)
> - [ ] Tests for the changes have been added (for bug fixes / features)
> - [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x")

> - [x] Bugfix
> - [ ] Feature
> - [ ] Code style update (formatting, local variables)
> - [ ] Refactoring (no functional changes, no api changes)
> - [ ] Build related changes
> - [ ] Documentation
> - [ ] Other... Please describe:

**What is the current behaviour?** (You can also link to an open issue here)
https://hyland.atlassian.net/browse/ACS-7555

**What is the new behaviour?**
Styles for column filters are corrected.

**Does this PR introduce a breaking change?** (check one with "x")

> - [ ] Yes
> - [x] No

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

**Other information**:
ACA PR: https://github.com/Alfresco/alfresco-content-app/pull/3813

### CODE REVIEW

**Comment by nikita-web-ua** [comment]
Do we need to add this blue border for accessibility? On migration it just becomes darker 
ACA:
Screenshot 2024-04-19 at 15 30 32
Migration:
Screenshot 2024-04-19 at 15 31 09

**Comment by nikita-web-ua** [comment]
guess can be changed already to `appearance="outline"`?
Screenshot 2024-04-19 at 15 43 08

**Comment by AleksanderSklorz** [comment]
> Do we need to add this blue border for accessibility? On migration it just becomes darker ACA: Screenshot 2024-04-19 at 15 30 32 Migration: Screenshot 2024-04-19 at 15 31 09

done

**Comment by AleksanderSklorz** [comment]
> guess can be changed already to `appearance="outline"`? Screenshot 2024-04-19 at 15 43 08

done

**Review by nikita-web-ua — APPROVED** [review]

**Review by MichalKinas — APPROVED** [review]

**Pull request merged**
