### PR TITLE
Add Japanese translation

### PR DESCRIPTION
**Pull request by silverskyvicto**
**Please check if the PR fulfills these requirements**

> - [ ] The commit message follows our [guidelines](https://github.com/Alfresco/alfresco-ng2-components/wiki/Commit-format)
> - [ ] Tests for the changes have been added (for bug fixes / features)
> - [x] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x")

> - [ ] Bugfix
> - [ ] Feature
> - [ ] Code style update (formatting, local variables)
> - [ ] Refactoring (no functional changes, no api changes)
> - [ ] Build related changes
> - [x] Documentation
> - [ ] Other... Please describe:

Partly translated the documentation into Japanese.

**What is the current behaviour?** (You can also link to an open issue here)
Documentation is English only.

**What is the new behaviour?**
Japanese documents can be selected

**Does this PR introduce a breaking change?** (check one with "x")

> - [ ] Yes
> - [x] No

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

**Other information**:

### CODE REVIEW

**Comment by eromano** [comment]
Hi @silverskyvicto Yuuki Ebihara thanks for your contribution. I will add also our translation team to check your contribution :) I am not really good with Japanese. 🇯🇵

**Comment by gbroadbent** [comment]
Hello @silverskyvicto Yuuki Ebihara, I am the Globalization Manager at Alfresco and responsible for all our localisation work.  I would like to also say thank you for your contribution.  May I ask if it was you who also translated some of the UI files for the Modeller app?  Also, regarding new translations for our docs, I would like to provide you with some guidelines in style and terminology so your work is consistent with our docs in Japanese and overall with all our Alfresco products. What would be the best way to get in touch?

**Comment by silverskyvicto** [comment]
Hi @gbroadbent Gloria Broadbent, Thank you for comment.

> May I ask if it was you who also translated some of the UI files for the Modeller app? 

Translated the Alfresco Content App documentation, not the Modeller app.
The pull request at that time is as follows.

- [Add Japanese document #1186](https://github.com/Alfresco/alfresco-content-app/pull/1186)

> What would be the best way to get in touch?

Please do one of the following:

- Github Issue
- Any chat tool (eg Slack, Mattermost, etc.)
- Mail

**Comment by gbroadbent** [comment]
Hello @silverskyvicto Yuuki Ebihara, thank you for your message with answers.  Are you aware that we have already localised the documentation for ACA/Alfresco Digital Workspace into 16 languages including Japanese? Please see: (https://docs.alfresco.com/adw-ja/concepts/welcome-adw.html) On the home page you just need to click on the language required.
As for the ADF documentation, we have not localised it but I would like you to check the ACA docs that we published so you can see the style that is used for Alfresco docs in Japanese.  Also please use the terminology for the UI that is in https://github.com/Alfresco/alfresco-ui-strings.  Please let me know if you have any questions. Any feedback is most welcome. Best regards,

**Comment by silverskyvicto** [comment]
Hi @gbroadbent Gloria Broadbent, Thanks for your comment.

> Are you aware that we have already localised the documentation for ACA/Alfresco Digital Workspace into 16 languages including Japanese? 
Please see: (https://docs.alfresco.com/adw-ja/concepts/welcome-adw.html) On the home page you just need to click on the language required.

Yes. I know that the Japanese document exists.
John told me in a comment on the issue below.

- [Japanese Documentation. #1178](https://github.com/Alfresco/alfresco-content-app/issues/1178)

> As for the ADF documentation, we have not localised it but I would like you to check the "ACA" docs that we published so you can see the style that is used for "Alfresco" docs in Japanese. Also please use the terminology for the UI that is in https://github.com/Alfresco/alfresco-ui-strings. 

OK. Not all documents can be checked immediately, but we will check them little by little.

> Please let me know if you have any questions. Any feedback is most welcome. 

I don't know if it's appropriate to write this issue because it's a different gist, but it would be very helpful to have the Alfresco Builder Network consolidate documents that are currently scattered around.

Currently, documents are scattered in the following places, so it is troublesome to find information.

1. docs.alfresco.com
2. Alfresco Builder Network
3. GitHub (It is described in Readme etc.)
4. netlify (ACA)
5. http://dev.alfresco.com/resource/docs/java/
6. http://dev.alfresco.com/resource/AlfrescoOne/5.1/PublicAPI/overview-summary.html

It is easy to understand if the documentation for developers is collected on Alfresco Builder Network and the documentation for users and administrators is collected on docs.alfresco.com.

I understand that it is not something we can do right away, but we want it to happen.

Thank you for your kind response.

**Comment by eromano** [comment]
I am closing the branch but don't I will not delete it, waiting to the instruction about how this thing can fit in the  documentation site

**Pull request closed without merging**
