### PR TITLE
[ACS-6819][FE] Document List View Header - move and resize columns icons are overlapping

### PR DESCRIPTION
**Pull request by tamaragruszka**
**Please check if the PR fulfills these requirements**

> - [x] The commit message follows our [guidelines](https://github.com/Alfresco/alfresco-ng2-components/wiki/Commit-format)
> - [ ] Tests for the changes have been added (for bug fixes / features)
> - [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x")

> - [x] Bugfix
> - [ ] Feature
> - [ ] Code style update (formatting, local variables)
> - [ ] Refactoring (no functional changes, no api changes)
> - [ ] Build related changes
> - [ ] Documentation
> - [ ] Other... Please describe:

**What is the current behaviour?** (You can also link to an open issue here)
Header icons move and resize are overlapping
[ACS-6819](https://alfresco.atlassian.net/browse/ACS-6819)

**What is the new behaviour?**
Header move and resize aren't overlapping

**Does this PR introduce a breaking change?** (check one with "x")

> - [ ] Yes
> - [x] No

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

**Other information**:

[ACS-6819]: https://alfresco.atlassian.net/browse/ACS-6819?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by AleksanderSklorz** [comment]
If you check files for specific library then "Modified" and "Modified by" headers are a bit not aligned in comparison with content of these columns. 
image

**Comment by AleksanderSklorz** [comment]
Please update PR's title with jira number: 
image

**Comment by AleksanderSklorz** [comment]
Columns in Favorite libraries are not aligned: 
image

**Comment by AleksanderSklorz** [comment]
Columns are not aligned in Favorites page: 
image

**Comment by AleksanderSklorz** [comment]
the same for Trash: 
image

**Comment by AleksanderSklorz** [comment]
same for personal files, some columns are not aligned properly: 
image

**Comment by AleksanderSklorz** [comment]
the same for Tasks: 
image

**Comment by AleksanderSklorz** [comment]
@tamaragruszka please go through all lists and correct where needed. I posted here only couple of examples.

**Review by DenysVuika — APPROVED** [review]

**Comment by tamaragruszka** [comment]
resolved by [ACS-6565](https://hyland.atlassian.net/browse/ACS-6565)

**Pull request closed without merging**
