### PR TITLE
[ADF-5009] close all the dialogs after false canActivate event

### PR DESCRIPTION
**Pull request by eromano**
**Please check if the PR fulfills these requirements**

> - [x] The commit message follows our [guidelines](https://github.com/Alfresco/alfresco-ng2-components/wiki/Commit-format)
> - [x] Tests for the changes have been added (for bug fixes / features)
> - [x] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x")

> - [x] Bugfix
> - [ ] Feature
> - [ ] Code style update (formatting, local variables)
> - [ ] Refactoring (no functional changes, no api changes)
> - [ ] Build related changes
> - [ ] Documentation
> - [ ] Other... Please describe:

**What is the current behaviour?** (You can also link to an open issue here)

All the open modal dialogs needs handling and closing when the user logs out.

**What is the new behaviour?**

**Does this PR introduce a breaking change?** (check one with "x")

> - [ ] Yes
> - [x] No

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

**Other information**:

### CODE REVIEW

**Comment by pionnegru** [comment]
shouldn't this be the responsibility of the app and not auth guard? AlfrescoApiService has ```.on('error')``` that can do the trick

**Comment by eromano** [comment]
> shouldn't this be the responsibility of the app and not auth guard? AlfrescoApiService has `.on('error')` that can do the trick

@pionnegru  I think the problem is that you can be redirected to the login also without error. 
There is another scenario when another tab logs out.
I anyway agree as concern doesn't really look the better place. Do you have another idea at the light of this other possible scenario?

**Comment by pionnegru** [comment]
I guess the app could listen for NavigationEnd event to be the login route

**Comment by eromano** [comment]
I tryed other way but they weren't working or were making the code even more complicate . I am still open to other suggestion otherwise I suggest to merge this

**Pull request merged**
