### PR TITLE
[ADF-5406] SCSS and HTML template path fixes

### PR DESCRIPTION
**Pull request by DenysVuika**
**Please check if the PR fulfills these requirements**

> - [x] The commit message follows our [guidelines](https://github.com/Alfresco/alfresco-ng2-components/wiki/Commit-format)
> - [ ] Tests for the changes have been added (for bug fixes / features)
> - [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x")

> - [x] Bugfix
> - [ ] Feature
> - [ ] Code style update (formatting, local variables)
> - [ ] Refactoring (no functional changes, no api changes)
> - [ ] Build related changes
> - [ ] Documentation
> - [ ] Other... Please describe:

**What is the current behaviour?** (You can also link to an open issue here)

**What is the new behaviour?**

**Important: This is a prerequisite for Angular 11/12 upgrade, it reduces the amount of efforts needed for upgrade**

- fix issues the `templateUrl` paths
- fix issues with the double scss bundling (mixins)
- reduce useless mixins where possible
- reduce `$mat-small` and `$mat-xsmall` (deprecated/removed in Angular 12)

**Does this PR introduce a breaking change?** (check one with "x")

> - [ ] Yes
> - [x] No

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

**Other information**:
https://alfresco.atlassian.net/browse/ADF-5406

### CODE REVIEW

**Review by pmartinezga — COMMENTED** [review]
Is it ok having this empty file demo-shell/src/app/components/cloud/start-process-cloud-demo.component.scss?

**Review by pmartinezga — COMMENTED** [review]
empty demo-shell/src/app/components/cloud/start-task-cloud-demo.component.scss?

**Comment by DenysVuika** [comment]
@pmartinezga empty css files is considered an anti-pattern from what I recall, and puts some pressure on the compile time

**Review by eromano — APPROVED** [review]

**Pull request merged**
