### PR TITLE
Addition to the preparation of the environment.

### PR DESCRIPTION
**Pull request by fcorti**
**Please check if the PR fulfills these requirements**

> - [ ] The commit message follows our [guidelines](https://github.com/Alfresco/alfresco-ng2-components/wiki/Commit-format)
> - [ ] Tests for the changes have been added (for bug fixes / features)
> - [*] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x")

> - [ ] Bugfix
> - [ ] Feature
> - [ ] Code style update (formatting, local variables)
> - [ ] Refactoring (no functional changes, no api changes)
> - [ ] Build related changes
> - [*] Documentation
> - [ ] Other... Please describe:

**What is the current behaviour?** (You can also link to an open issue here)
N/A

**What is the new behaviour?**
N/A

**Does this PR introduce a breaking change?** (check one with "x")

> - [ ] Yes
> - [*] No

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

**Other information**:
This PR contains the addition of the working-with-nodes-api-service tutorial (already reviewed) and the extension of the preparation of the environment with the ACS/APS/ACA installation.

### CODE REVIEW

**Comment by fcorti** [comment]
Hi @therealandeeee,

This PR contains the addition of the working-with-nodes-api-service tutorial (already reviewed) and the extension of the preparation of the environment with the ACS/APS/ACA installation.

For the next PR I think I'll use a different branch to avoid to review again the same stuff.
Please let me know if you have a different suggestion.

**Comment by fcorti** [comment]
Do you know why the @codecov-io fails?
Is it something we can ignore or is it something I should face to avoid the failure?
Thank you in advance for the support.

**Comment by DenisVuyka** [comment]
@fcorti you can ignore that for now. Sometimes it goes crazy after rebases :)

**Comment by fcorti** [comment]
Ok, thank you @DenisVuyka for the clarification.

**Pull request merged**
