### PR TITLE
[ADF-4633] DemoShell - MatIcon directionality

### PR DESCRIPTION
**Pull request by pionnegru**
**Please check if the PR fulfills these requirements**

> - [x] The commit message follows our [guidelines](https://github.com/Alfresco/alfresco-ng2-components/wiki/Commit-format)
> - [ ] Tests for the changes have been added (for bug fixes / features)
> - [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x")

> - [ ] Bugfix
> - [x] Feature
> - [ ] Code style update (formatting, local variables)
> - [ ] Refactoring (no functional changes, no api changes)
> - [ ] Build related changes
> - [ ] Documentation
> - [ ] Other... Please describe:

**What is the current behaviour?** (You can also link to an open issue here)
[ADF-4633](https://issues.alfresco.com/jira/browse/ADF-4633)

**What is the new behaviour?**

**Does this PR introduce a breaking change?** (check one with "x")

> - [ ] Yes
> - [x] No

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

**Other information**:
[mat-icon](https://material.angular.io/components/icon/overview#bidirectionality) doesn't support directionality out of the box and manually adding the proposed class to every icon and remembering to do this its an overload. 

❗️ Documentation for this change has been documented in https://github.com/Alfresco/alfresco-ng2-components/pull/4814

### CODE REVIEW

**Comment by pionnegru** [comment]
it's the same code https://github.com/angular/components/blob/master/src/material/icon/icon.scss#L23

**Comment by DenysVuika** [comment]
The problem I see here is that it's just demo shell thing, all external apps won't benefit from this change. Can we do the same for "adf-icon" component we have?

**Comment by pionnegru** [comment]
the documentation mentions about this https://github.com/Alfresco/alfresco-ng2-components/pull/4814/files#diff-97445eafb69a134454fe27cd27f8126dR76 as a tradeoff

**Comment by pionnegru** [comment]
adf-icon should be affected too by this, but we can make it more specific?

**Pull request merged**
