### PR TITLE
[ADF-5156] Name column fixes

### PR DESCRIPTION
**Pull request by DenysVuika**
**Please check if the PR fulfills these requirements**

> - [x] The commit message follows our [guidelines](https://github.com/Alfresco/alfresco-ng2-components/wiki/Commit-format)
> - [x] Tests for the changes have been added (for bug fixes / features)
> - [x] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x")

> - [x] Bugfix
> - [ ] Feature
> - [ ] Code style update (formatting, local variables)
> - [ ] Refactoring (no functional changes, no api changes)
> - [ ] Build related changes
> - [ ] Documentation
> - [ ] Other... Please describe:

**What is the current behaviour?** (You can also link to an open issue here)

**What is the new behaviour?**

- use column key to resolve the name value
- add additional unit tests
- fix copyright year

**Does this PR introduce a breaking change?** (check one with "x")

> - [ ] Yes
> - [x] No

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

**Other information**:
https://alfresco.atlassian.net/browse/ADF-5156

### CODE REVIEW

**Review by eromano — CHANGES_REQUESTED** [review]
Do we need to update any doc?

**Comment by DenysVuika** [comment]
> Do we need to update any doc?

I've updated the `docs/content-services/components/document-list.component.md` file to reflect the `key`

**Review by davidcanonieto — APPROVED** [review]

**Comment by DenysVuika** [comment]
@eromano is the .md change enough? can we merge this PR?

**Review by eromano — APPROVED** [review]

**Pull request merged**
