### PR TITLE
[AAE-19610] Submit query on change event for search date range tabbed widget

### PR DESCRIPTION
**Pull request by DiogoABastos**
**Please check if the PR fulfills these requirements**

> - [x] The commit message follows our [guidelines](https://github.com/Alfresco/alfresco-ng2-components/wiki/Commit-format)
> - [ ] Tests for the changes have been added (for bug fixes / features)
> - [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x")

> - [x] Bugfix
> - [ ] Feature
> - [ ] Code style update (formatting, local variables)
> - [ ] Refactoring (no functional changes, no api changes)
> - [ ] Build related changes
> - [ ] Documentation
> - [ ] Other... Please describe:

**What is the current behaviour?** (You can also link to an open issue here)

**What is the new behaviour?**

**Does this PR introduce a breaking change?** (check one with "x")

> - [ ] Yes
> - [x] No

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

**Other information**:

### CODE REVIEW

**Review by BSekula — APPROVED** [review]

**Review by eromano — APPROVED** [review]

**Comment by swapnil-verma-gl** [comment]
Having a submitValues() call inside onDateChanged() method is causing the search query to be unnecessarily triggered while the user is still setting values and not finished is input yet in ACA/ADW. See video below - 

https://github.com/Alfresco/alfresco-ng2-components/assets/92505353/05eea189-062d-42c9-8f2a-10aabe9912f6

**Comment by DiogoABastos** [comment]
I've added a `debounceTime` to the form's valueChanges event which seems to have fixed the multiple search call issue. However, based on your video, we should only call the submitValues method if `hideDefaultActions` is true, so we avoid calling the search query when the apply button is available, right? @swapnil-verma-gl 
`if (settings.hideDefaultActions) this.submitValues();`

**Comment by swapnil-verma-gl** [comment]
> I've added a `debounceTime` to the form's valueChanges event which seems to have fixed the multiple search call issue. However, based on your video, we should only call the submitValues method if `hideDefaultActions` is true, so we avoid calling the search query when the apply button is available, right? @swapnil-verma-gl `if (settings.hideDefaultActions) this.submitValues();`

I don't think the Clear and Apply buttons being shown here come from the hideDefaultActions parameter being false. They are separate buttons, being projected through [search-widget-chip.component](https://github.com/Alfresco/alfresco-ng2-components/blob/develop/lib/content-services/src/lib/search/components/search-filter-chips/search-widget-chip/search-widget-chip.component.html#L41). So adding the if condition as you proposed wouldn't really have any effect.

Would it serve your purpose if you were to go back to your original approach of creating the default actions buttons inside the search filter. That way, we can simply toggle the default actions to OFF via the hideDefaultActions parameter, thereby ensuring that none of the changes impact ACA/ADW

**Comment by DiogoABastos** [comment]
> Would it serve your purpose if you were to go back to your original approach of creating the default actions buttons inside the search filter. That way, we can simply toggle the default actions to OFF via the hideDefaultActions parameter, thereby ensuring that none of the changes impact ACA/ADW

We want to have this component submit the value on change rather than using the buttons. With this solution, will it impact ACA/ADW?

**Review by eromano — APPROVED** [review]

**Pull request merged**
