### PR TITLE
Add upload callback for adf-version-manager

### PR DESCRIPTION
**Pull request by chen2584**
**Please check if the PR fulfills these requirements**

> - [X] The commit message follows our [guidelines](https://github.com/Alfresco/alfresco-ng2-components/wiki/Commit-format)
> - [X] Tests for the changes have been added (for bug fixes / features)
> - [X] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x")

> - [ ] Bugfix
> - [X] Feature
> - [ ] Code style update (formatting, local variables)
> - [ ] Refactoring (no functional changes, no api changes)
> - [ ] Build related changes
> - [ ] Documentation
> - [ ] Other... Please describe:

**What is the current behaviour?** (You can also link to an open issue here)
No callback on VersionUploadComponent and VersionManagerComponent. User will not know when file is uploaded or error occurs.

**What is the new behaviour?**
Add success and error EvenEmitter to VersionUploadComponent. Add uploadSuccess and uploadError EventEmiiter to VersionManagerComponent.

These EventEmitter will let developer custom thier callback function. For example, Refresh component when file version is uploaded

**Does this PR introduce a breaking change?** (check one with "x")

> - [ ] Yes
> - [X] No

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

**Other information**:

### CODE REVIEW

**Comment by eromano** [comment]
Hi @chen2584 thanks for your PR. 
You should change the target branch to development
https://github.com/Alfresco/alfresco-ng2-components/wiki/Branching-Strategy

**Comment by chen2584** [comment]
This is my first time PR. I afraid if i change branch to development, 

screen shot 2561-02-27 at 5 28 19 pm

**Comment by eromano** [comment]
I think is easy if you close this PR and you create a new PR starting from development charring pick the modify or copy paste it

**Comment by chen2584** [comment]
Sure @eromano, I will do it

**Comment by eromano** [comment]
thanks

**Pull request closed without merging**
