### PR TITLE
[AAE-4203] [ADW+APA] Destination picker's breadcrumb on search is displaying the path of the selected document

### PR DESCRIPTION
**Pull request by sivakumar414ram**
**Please check if the PR fulfills these requirements**

> - [x] The commit message follows our [guidelines](https://github.com/Alfresco/alfresco-ng2-components/wiki/Commit-format)
> - [ ] Tests for the changes have been added (for bug fixes / features)
> - [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x")

> - [x] Bugfix
> - [ ] Feature
> - [ ] Code style update (formatting, local variables)
> - [ ] Refactoring (no functional changes, no api changes)
> - [ ] Build related changes
> - [ ] Documentation
> - [ ] Other... Please describe:

**What is the current behaviour?** (You can also link to an open issue here)

https://alfresco.atlassian.net/browse/AAE-4203

**What is the new behaviour?**

**Does this PR introduce a breaking change?** (check one with "x")

> - [ ] Yes
> - [x] No

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

**Other information**:

### CODE REVIEW

**Review by eromano — CHANGES_REQUESTED** [review]
can we  have a unit test?

**Comment by sivakumar414ram** [comment]
> can we have a unit test?

Added unit test

**Review by arditdomi — APPROVED** [review]

**Comment by arditdomi** [comment]
@sivakumar414ram the unit tests seem to be failing for a reason there is no need to rebase and restart the run. https://travis-ci.com/github/Alfresco/alfresco-ng2-components/jobs/450800712#L2301

**Comment by sivakumar414ram** [comment]
> @sivakumar414ram the unit tests seem to be failing for a reason. https://travis-ci.com/github/Alfresco/alfresco-ng2-components/jobs/450800712#L2301

Fixed failing test

**Comment by sivakumar414ram** [comment]
Closing this pr for now, will create a new one. Thanks

**Pull request closed without merging**
