### PR TITLE
[ACA-4197] always redirect authenticated users to success route

### PR DESCRIPTION
**Pull request by DenysVuika**
**Please check if the PR fulfills these requirements**

> - [x] The commit message follows our [guidelines](https://github.com/Alfresco/alfresco-ng2-components/wiki/Commit-format)
> - [ ] Tests for the changes have been added (for bug fixes / features)
> - [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x")

> - [x] Bugfix
> - [ ] Feature
> - [ ] Code style update (formatting, local variables)
> - [ ] Refactoring (no functional changes, no api changes)
> - [ ] Build related changes
> - [ ] Documentation
> - [ ] Other... Please describe:

**What is the current behaviour?** (You can also link to an open issue here)

**What is the new behaviour?**

- always redirect authenticated users to the `successRoute`
- cleanup login code
- cleanup demo shell login wrapper (remove toggles that were used by obsolete e2e, already covered by unit tests)
- remove e2e that already have unit tests
- remove useless login e2e (checking image in demo shell without asserts, etc)

**Does this PR introduce a breaking change?** (check one with "x")

> - [ ] Yes
> - [x] No

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

**Other information**:
https://alfresco.atlassian.net/browse/ACA-4197

### CODE REVIEW

**Review by eromano — APPROVED** [review]

**Comment by eromano** [comment]
can we wait before my pr? I may have already a fix for this problem as well

**Comment by DenysVuika** [comment]
Of course we can wait, lots of e2e failing with this one :)

**Pull request closed without merging**
